# Generated by Django 4.0.4 on 2022-05-29 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactus',
        ),
    ]
